### ISSUE TITLE
adb已经连接手机，但是代码一直报错（python3.6环境）

### ISSUE THREAD

**Issue by shirleyxyli** [williamfzc/fitch#2]
adb已经连接手机，但是代码一直报错（python3.6环境）
![image](https://user-images.githubusercontent.com/19338744/56025282-67137b00-5d44-11e9-9beb-2037fb4829b5.png)

**Comment by williamfzc** [comment]
看起来是minitouch出了点问题，这边可能需要一些额外的信息：

1. 你先试一下minitouch是否正常运行：

```bash
adb shell /data/local/tmp/minitouch
```

正常来说会提示：

```text
Type B touch device touchpanel (1080x2280 with 10 contacts) detected on /dev/input/event1 (score 22578)
```

2. 在代码中打开logger开关，在代码中加入：

```python
from fitch.logger import logger
logger.enable('pyminitouch')
```

然后将完整日志贴上来~

3. 你使用的具体手机型号是？
